/* FILE GENERATED AUTOMATICALLY, DO NOT EDIT */

#include <gurobi_c.h>
#include "GRBMILPSolver.h"

using namespace SMSpp_di_unipi_it;

const std::array< std::string, GRB_NUM_INT_PARS > GRBMILPSolver::SMSpp_to_GUROBI_int_pars{
 "SolutionLimit",
 "Method",
 "ConcurrentMethod",
 "ScaleFlag",
 "SimplexPricing",
 "Quad",
 "NormAdjust",
 "SiftMethod",
 "Sifting",
 "LPWarmStart",
 "NetworkAlg",
 "BarIterLimit",
 "BarCorrectors",
 "BarHomogeneous",
 "BarOrder",
 "Crossover",
 "CrossoverBasis",
 "BranchDir",
 "DegenMoves",
 "Disconnected",
 "IntegralityFocus",
 "MinRelNodes",
 "MIPFocus",
 "NodeMethod",
 "OBBT",
 "PumpPasses",
 "RINS",
 "NLPHeur",
 "SolutionNumber",
 "StartNodeLimit",
 "SubMIPNodes",
 "Symmetry",
 "VarBranch",
 "ZeroObjNodes",
 "Cuts",
 "CutPasses",
 "CliqueCuts",
 "CoverCuts",
 "CutAggPasses",
 "FlowCoverCuts",
 "FlowPathCuts",
 "GomoryPasses",
 "GUBCoverCuts",
 "ImpliedCuts",
 "ProjImpliedCuts",
 "MIPSepCuts",
 "MIRCuts",
 "StrongCGCuts",
 "NetworkCuts",
 "SubMIPCuts",
 "ZeroHalfCuts",
 "ModKCuts",
 "InfProofCuts",
 "RLTCuts",
 "RelaxLiftCuts",
 "BQPCuts",
 "PSDCuts",
 "LiftProjectCuts",
 "MixingCuts",
 "ServerTimeout",
 "CSPriority",
 "CSIdleTimeout",
 "CSTLSInsecure",
 "TSPort",
 "CSBatchMode",
 "CSClientLog",
 "WLSTokenDuration",
 "LicenseID",
 "Aggregate",
 "AggFill",
 "PreDual",
 "ConcurrentMIP",
 "ConcurrentJobs",
 "DisplayInterval",
 "DistributedMIPJobs",
 "DualReductions",
 "IISMethod",
 "InfUnbdInfo",
 "JSONSolDetail",
 "LogToConsole",
 "MIQCPMethod",
 "NonConvex",
 "NumericFocus",
 "QCPDual",
 "PreCrush",
 "PreDepRow",
 "PreQLinearize",
 "PrePasses",
 "Presolve",
 "PreSOS1Encoding",
 "PreSOS2Encoding",
 "PreSparsify",
 "PreMIQCPForm",
 "Seed",
 "SolutionTarget",
 "Threads",
 "LazyConstraints",
 "TuneResults",
 "TuneCriterion",
 "TuneTrials",
 "TuneOutput",
 "TuneJobs",
 "TuneMetric",
 "TuneDynamicJobs",
 "UpdateMode",
 "ObjNumber",
 "MultiObjMethod",
 "MultiObjPre",
 "ScenarioNumber",
 "Record",
 "PoolSolutions",
 "PoolSearchMode",
 "IgnoreNames",
 "StartNumber",
 "PartitionPlace",
 "FuncPieces",
 "FuncNonlinear",
 "OutputFlag",
};

const std::array< std::string, GRB_NUM_DBL_PARS > GRBMILPSolver::SMSpp_to_GUROBI_dbl_pars{
 "Cutoff",
 "IterationLimit",
 "NodeLimit",
 "TimeLimit",
 "WorkLimit",
 "MemLimit",
 "SoftMemLimit",
 "BestObjStop",
 "BestBdStop",
 "FeasibilityTol",
 "IntFeasTol",
 "MarkowitzTol",
 "MIPGap",
 "MIPGapAbs",
 "OptimalityTol",
 "PSDTol",
 "PerturbValue",
 "ObjScale",
 "BarConvTol",
 "BarQCPConvTol",
 "Heuristics",
 "NodefileStart",
 "NoRelHeurTime",
 "NoRelHeurWork",
 "CSQueueTimeout",
 "WLSTokenRefresh",
 "PreSOS1BigM",
 "PreSOS2BigM",
 "FeasRelaxBigM",
 "ImproveStartTime",
 "ImproveStartGap",
 "ImproveStartNodes",
 "TuneTimeLimit",
 "TuneCleanup",
 "TuneTargetMIPGap",
 "TuneTargetTime",
 "PoolGap",
 "PoolGapAbs",
 "FuncPieceLength",
 "FuncPieceError",
 "FuncPieceRatio",
 "FuncMaxVal",
};

const std::array< std::string, GRB_NUM_STR_PARS > GRBMILPSolver::SMSpp_to_GUROBI_str_pars{
 "NodefileDir",
 "SolFiles",
 "WorkerPool",
 "WorkerPassword",
 "ComputeServer",
 "JobID",
 "CSRouter",
 "CSGroup",
 "ServerPassword",
 "TokenServer",
 "CloudAccessID",
 "CloudSecretKey",
 "CloudPool",
 "CloudHost",
 "CSManager",
 "CSAuthToken",
 "CSAPIAccessID",
 "CSAPISecret",
 "Username",
 "CSAppName",
 "WLSAccessID",
 "WLSSecret",
 "WLSToken",
 "LogFile",
 "ResultFile",
 "Dummy",
};

const std::array< std::pair< std::string, int >, GRB_NUM_INT_PARS >
 GRBMILPSolver::GUROBI_to_SMSpp_int_pars{
 {
  { "SolutionLimit", intFirstGUROBIPar + 0 },
  { "Method", intFirstGUROBIPar + 1 },
  { "ConcurrentMethod", intFirstGUROBIPar + 2 },
  { "ScaleFlag", intFirstGUROBIPar + 3 },
  { "SimplexPricing", intFirstGUROBIPar + 4 },
  { "Quad", intFirstGUROBIPar + 5 },
  { "NormAdjust", intFirstGUROBIPar + 6 },
  { "SiftMethod", intFirstGUROBIPar + 7 },
  { "Sifting", intFirstGUROBIPar + 8 },
  { "LPWarmStart", intFirstGUROBIPar + 9 },
  { "NetworkAlg", intFirstGUROBIPar + 10 },
  { "BarIterLimit", intFirstGUROBIPar + 11 },
  { "BarCorrectors", intFirstGUROBIPar + 12 },
  { "BarHomogeneous", intFirstGUROBIPar + 13 },
  { "BarOrder", intFirstGUROBIPar + 14 },
  { "Crossover", intFirstGUROBIPar + 15 },
  { "CrossoverBasis", intFirstGUROBIPar + 16 },
  { "BranchDir", intFirstGUROBIPar + 17 },
  { "DegenMoves", intFirstGUROBIPar + 18 },
  { "Disconnected", intFirstGUROBIPar + 19 },
  { "IntegralityFocus", intFirstGUROBIPar + 20 },
  { "MinRelNodes", intFirstGUROBIPar + 21 },
  { "MIPFocus", intFirstGUROBIPar + 22 },
  { "NodeMethod", intFirstGUROBIPar + 23 },
  { "OBBT", intFirstGUROBIPar + 24 },
  { "PumpPasses", intFirstGUROBIPar + 25 },
  { "RINS", intFirstGUROBIPar + 26 },
  { "NLPHeur", intFirstGUROBIPar + 27 },
  { "SolutionNumber", intFirstGUROBIPar + 28 },
  { "StartNodeLimit", intFirstGUROBIPar + 29 },
  { "SubMIPNodes", intFirstGUROBIPar + 30 },
  { "Symmetry", intFirstGUROBIPar + 31 },
  { "VarBranch", intFirstGUROBIPar + 32 },
  { "ZeroObjNodes", intFirstGUROBIPar + 33 },
  { "Cuts", intFirstGUROBIPar + 34 },
  { "CutPasses", intFirstGUROBIPar + 35 },
  { "CliqueCuts", intFirstGUROBIPar + 36 },
  { "CoverCuts", intFirstGUROBIPar + 37 },
  { "CutAggPasses", intFirstGUROBIPar + 38 },
  { "FlowCoverCuts", intFirstGUROBIPar + 39 },
  { "FlowPathCuts", intFirstGUROBIPar + 40 },
  { "GomoryPasses", intFirstGUROBIPar + 41 },
  { "GUBCoverCuts", intFirstGUROBIPar + 42 },
  { "ImpliedCuts", intFirstGUROBIPar + 43 },
  { "ProjImpliedCuts", intFirstGUROBIPar + 44 },
  { "MIPSepCuts", intFirstGUROBIPar + 45 },
  { "MIRCuts", intFirstGUROBIPar + 46 },
  { "StrongCGCuts", intFirstGUROBIPar + 47 },
  { "NetworkCuts", intFirstGUROBIPar + 48 },
  { "SubMIPCuts", intFirstGUROBIPar + 49 },
  { "ZeroHalfCuts", intFirstGUROBIPar + 50 },
  { "ModKCuts", intFirstGUROBIPar + 51 },
  { "InfProofCuts", intFirstGUROBIPar + 52 },
  { "RLTCuts", intFirstGUROBIPar + 53 },
  { "RelaxLiftCuts", intFirstGUROBIPar + 54 },
  { "BQPCuts", intFirstGUROBIPar + 55 },
  { "PSDCuts", intFirstGUROBIPar + 56 },
  { "LiftProjectCuts", intFirstGUROBIPar + 57 },
  { "MixingCuts", intFirstGUROBIPar + 58 },
  { "ServerTimeout", intFirstGUROBIPar + 59 },
  { "CSPriority", intFirstGUROBIPar + 60 },
  { "CSIdleTimeout", intFirstGUROBIPar + 61 },
  { "CSTLSInsecure", intFirstGUROBIPar + 62 },
  { "TSPort", intFirstGUROBIPar + 63 },
  { "CSBatchMode", intFirstGUROBIPar + 64 },
  { "CSClientLog", intFirstGUROBIPar + 65 },
  { "WLSTokenDuration", intFirstGUROBIPar + 66 },
  { "LicenseID", intFirstGUROBIPar + 67 },
  { "Aggregate", intFirstGUROBIPar + 68 },
  { "AggFill", intFirstGUROBIPar + 69 },
  { "PreDual", intFirstGUROBIPar + 70 },
  { "ConcurrentMIP", intFirstGUROBIPar + 71 },
  { "ConcurrentJobs", intFirstGUROBIPar + 72 },
  { "DisplayInterval", intFirstGUROBIPar + 73 },
  { "DistributedMIPJobs", intFirstGUROBIPar + 74 },
  { "DualReductions", intFirstGUROBIPar + 75 },
  { "IISMethod", intFirstGUROBIPar + 76 },
  { "InfUnbdInfo", intFirstGUROBIPar + 77 },
  { "JSONSolDetail", intFirstGUROBIPar + 78 },
  { "LogToConsole", intFirstGUROBIPar + 79 },
  { "MIQCPMethod", intFirstGUROBIPar + 80 },
  { "NonConvex", intFirstGUROBIPar + 81 },
  { "NumericFocus", intFirstGUROBIPar + 82 },
  { "QCPDual", intFirstGUROBIPar + 83 },
  { "PreCrush", intFirstGUROBIPar + 84 },
  { "PreDepRow", intFirstGUROBIPar + 85 },
  { "PreQLinearize", intFirstGUROBIPar + 86 },
  { "PrePasses", intFirstGUROBIPar + 87 },
  { "Presolve", intFirstGUROBIPar + 88 },
  { "PreSOS1Encoding", intFirstGUROBIPar + 89 },
  { "PreSOS2Encoding", intFirstGUROBIPar + 90 },
  { "PreSparsify", intFirstGUROBIPar + 91 },
  { "PreMIQCPForm", intFirstGUROBIPar + 92 },
  { "Seed", intFirstGUROBIPar + 93 },
  { "SolutionTarget", intFirstGUROBIPar + 94 },
  { "Threads", intFirstGUROBIPar + 95 },
  { "LazyConstraints", intFirstGUROBIPar + 96 },
  { "TuneResults", intFirstGUROBIPar + 97 },
  { "TuneCriterion", intFirstGUROBIPar + 98 },
  { "TuneTrials", intFirstGUROBIPar + 99 },
  { "TuneOutput", intFirstGUROBIPar + 100 },
  { "TuneJobs", intFirstGUROBIPar + 101 },
  { "TuneMetric", intFirstGUROBIPar + 102 },
  { "TuneDynamicJobs", intFirstGUROBIPar + 103 },
  { "UpdateMode", intFirstGUROBIPar + 104 },
  { "ObjNumber", intFirstGUROBIPar + 105 },
  { "MultiObjMethod", intFirstGUROBIPar + 106 },
  { "MultiObjPre", intFirstGUROBIPar + 107 },
  { "ScenarioNumber", intFirstGUROBIPar + 108 },
  { "Record", intFirstGUROBIPar + 109 },
  { "PoolSolutions", intFirstGUROBIPar + 110 },
  { "PoolSearchMode", intFirstGUROBIPar + 111 },
  { "IgnoreNames", intFirstGUROBIPar + 112 },
  { "StartNumber", intFirstGUROBIPar + 113 },
  { "PartitionPlace", intFirstGUROBIPar + 114 },
  { "FuncPieces", intFirstGUROBIPar + 115 },
  { "FuncNonlinear", intFirstGUROBIPar + 116 },
  { "OutputFlag", intFirstGUROBIPar + 117 },
 }
};

const std::array< std::pair< std::string, int >, GRB_NUM_DBL_PARS >
 GRBMILPSolver::GUROBI_to_SMSpp_dbl_pars{
 {
  { "Cutoff", dblFirstGUROBIPar + 0 },
  { "IterationLimit", dblFirstGUROBIPar + 1 },
  { "NodeLimit", dblFirstGUROBIPar + 2 },
  { "TimeLimit", dblFirstGUROBIPar + 3 },
  { "WorkLimit", dblFirstGUROBIPar + 4 },
  { "MemLimit", dblFirstGUROBIPar + 5 },
  { "SoftMemLimit", dblFirstGUROBIPar + 6 },
  { "BestObjStop", dblFirstGUROBIPar + 7 },
  { "BestBdStop", dblFirstGUROBIPar + 8 },
  { "FeasibilityTol", dblFirstGUROBIPar + 9 },
  { "IntFeasTol", dblFirstGUROBIPar + 10 },
  { "MarkowitzTol", dblFirstGUROBIPar + 11 },
  { "MIPGap", dblFirstGUROBIPar + 12 },
  { "MIPGapAbs", dblFirstGUROBIPar + 13 },
  { "OptimalityTol", dblFirstGUROBIPar + 14 },
  { "PSDTol", dblFirstGUROBIPar + 15 },
  { "PerturbValue", dblFirstGUROBIPar + 16 },
  { "ObjScale", dblFirstGUROBIPar + 17 },
  { "BarConvTol", dblFirstGUROBIPar + 18 },
  { "BarQCPConvTol", dblFirstGUROBIPar + 19 },
  { "Heuristics", dblFirstGUROBIPar + 20 },
  { "NodefileStart", dblFirstGUROBIPar + 21 },
  { "NoRelHeurTime", dblFirstGUROBIPar + 22 },
  { "NoRelHeurWork", dblFirstGUROBIPar + 23 },
  { "CSQueueTimeout", dblFirstGUROBIPar + 24 },
  { "WLSTokenRefresh", dblFirstGUROBIPar + 25 },
  { "PreSOS1BigM", dblFirstGUROBIPar + 26 },
  { "PreSOS2BigM", dblFirstGUROBIPar + 27 },
  { "FeasRelaxBigM", dblFirstGUROBIPar + 28 },
  { "ImproveStartTime", dblFirstGUROBIPar + 29 },
  { "ImproveStartGap", dblFirstGUROBIPar + 30 },
  { "ImproveStartNodes", dblFirstGUROBIPar + 31 },
  { "TuneTimeLimit", dblFirstGUROBIPar + 32 },
  { "TuneCleanup", dblFirstGUROBIPar + 33 },
  { "TuneTargetMIPGap", dblFirstGUROBIPar + 34 },
  { "TuneTargetTime", dblFirstGUROBIPar + 35 },
  { "PoolGap", dblFirstGUROBIPar + 36 },
  { "PoolGapAbs", dblFirstGUROBIPar + 37 },
  { "FuncPieceLength", dblFirstGUROBIPar + 38 },
  { "FuncPieceError", dblFirstGUROBIPar + 39 },
  { "FuncPieceRatio", dblFirstGUROBIPar + 40 },
  { "FuncMaxVal", dblFirstGUROBIPar + 41 },
 }
};

const std::array< std::pair< std::string, int >, GRB_NUM_STR_PARS >
 GRBMILPSolver::GUROBI_to_SMSpp_str_pars{
 {
  { "NodefileDir", strFirstGUROBIPar + 0 },
  { "SolFiles", strFirstGUROBIPar + 1 },
  { "WorkerPool", strFirstGUROBIPar + 2 },
  { "WorkerPassword", strFirstGUROBIPar + 3 },
  { "ComputeServer", strFirstGUROBIPar + 4 },
  { "JobID", strFirstGUROBIPar + 5 },
  { "CSRouter", strFirstGUROBIPar + 6 },
  { "CSGroup", strFirstGUROBIPar + 7 },
  { "ServerPassword", strFirstGUROBIPar + 8 },
  { "TokenServer", strFirstGUROBIPar + 9 },
  { "CloudAccessID", strFirstGUROBIPar + 10 },
  { "CloudSecretKey", strFirstGUROBIPar + 11 },
  { "CloudPool", strFirstGUROBIPar + 12 },
  { "CloudHost", strFirstGUROBIPar + 13 },
  { "CSManager", strFirstGUROBIPar + 14 },
  { "CSAuthToken", strFirstGUROBIPar + 15 },
  { "CSAPIAccessID", strFirstGUROBIPar + 16 },
  { "CSAPISecret", strFirstGUROBIPar + 17 },
  { "Username", strFirstGUROBIPar + 18 },
  { "CSAppName", strFirstGUROBIPar + 19 },
  { "WLSAccessID", strFirstGUROBIPar + 20 },
  { "WLSSecret", strFirstGUROBIPar + 21 },
  { "WLSToken", strFirstGUROBIPar + 22 },
  { "LogFile", strFirstGUROBIPar + 23 },
  { "ResultFile", strFirstGUROBIPar + 24 },
  { "Dummy", strFirstGUROBIPar + 25 },
 }
};
