/* FILE GENERATED AUTOMATICALLY, DO NOT EDIT */

#ifndef __GRB1003_DEFS
#define __GRB1003_DEFS

#define GRB_NUM_INT_PARS 114
#define GRB_NUM_DBL_PARS 42
#define GRB_NUM_STR_PARS 26

#endif //__GRB1003_DEFS
