/* FILE GENERATED AUTOMATICALLY, DO NOT EDIT */

#ifndef __GRB1101_DEFS
#define __GRB1101_DEFS

#define GRB_NUM_INT_PARS 118
#define GRB_NUM_DBL_PARS 42
#define GRB_NUM_STR_PARS 26

#endif //__GRB1101_DEFS
