/* FILE GENERATED AUTOMATICALLY, DO NOT EDIT */

#ifndef __HiGHS153_DEFS
#define __HiGHS153_DEFS

#define HiGHS_NUM_INT_PARS 65
#define HiGHS_NUM_DBL_PARS 26
#define HiGHS_NUM_STR_PARS 10

#endif //__HiGHS153_DEFS
