/* FILE GENERATED AUTOMATICALLY, DO NOT EDIT */

#ifndef __SCIP703_DEFS
#define __SCIP703_DEFS

#define SCIP_NUM_INT_PARS 189
#define SCIP_NUM_DBL_PARS 71
#define SCIP_NUM_STR_PARS 18

#endif //__SCIP703_DEFS
