/* FILE GENERATED AUTOMATICALLY, DO NOT EDIT */

#ifndef __SCIP804_DEFS
#define __SCIP804_DEFS

#define SCIP_NUM_INT_PARS 194
#define SCIP_NUM_DBL_PARS 66
#define SCIP_NUM_STR_PARS 18

#endif //__SCIP804_DEFS
