/* FILE GENERATED AUTOMATICALLY, DO NOT EDIT */

#ifndef __SCIP800_DEFS
#define __SCIP800_DEFS

#define SCIP_NUM_INT_PARS 193
#define SCIP_NUM_DBL_PARS 66
#define SCIP_NUM_STR_PARS 18

#endif //__SCIP800_DEFS
