/* FILE GENERATED AUTOMATICALLY, DO NOT EDIT */

#ifndef __SCIP810_DEFS
#define __SCIP810_DEFS

#define SCIP_NUM_INT_PARS 194
#define SCIP_NUM_DBL_PARS 66
#define SCIP_NUM_STR_PARS 18

#endif //__SCIP810_DEFS
